FROM arm64v8/python:3.11-alpine@sha256:f7251fe0c6472a28a9ad1c899890bc3acd8b815aeeb10a5ae578451d468c1b96

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="docker-autotag"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/docker-autotag"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/docker-autotag"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/docker-autotag"

ENV PY_COLORS=1
ENV TZ=UTC

ADD dist/docker_autotag-*.whl /

RUN apk --update add --virtual .build-deps build-base libffi-dev openssl-dev && \
    apk --update add git && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir $(find / -name "docker_autotag-*.whl") && \
    apk del .build-deps && \
    rm -f docker_autotag-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/docker-autotag"]
